apiVersion: apps/v1
kind: Deployment
metadata:
  name: distcc
  namespace: default
spec:
  replicas: 6  # Based on available cores and RAM
  selector:
    matchLabels:
      app: distcc
  template:
    metadata:
      labels:
        app: distcc
    spec:
      containers:
        - name: distcc
          image: ksmanis/gentoo-distcc:tcp
          ports:
            - containerPort: 3632
          env:
            - name: DISTCC_ALLOW_HOSTS
              value: "192.168.0.0/16"  # Allow only LAN connections
          resources:
            limits:
              cpu: "1"     # Limit each container to 1 core
              memory: "4Gi"  # Allocate 4GB memory per container
            requests:
              cpu: "1"
              memory: "2Gi"
